language: node_js
node_js:
  - "5.0.0" #all the versions you want to be tested
branches:
  only:
    - master #all the branches that will trigger travis
    - develop
    - staging
before_install:
  - npm install -g gaston #as we use gaston to test we need to install it beforehand
  - npm install -g vigour-sentinel #required
script:
  - sentinel #required
after_failure:
  - sentinel --notify-fail #required
sudo: required
services:
  - docker
